#@pyrolyze

"""Generated UI interface stubs for discovered widgets."""

from __future__ import annotations

import PySide6

from typing import Any, ClassVar

from frozendict import frozendict

from pyrolyze.api import MISSING, MissingType, MountSelector, PyrolyzeHandler, UIElement, call_native, pyrolyze, ui_interface
from pyrolyze.backends.model import (
    AccessorKind,
    ChildPolicy,
    EventPayloadPolicy,
    FillPolicy,
    MethodMode,
    MountReplayKind,
    MountParamSpec,
    MountPointSpec,
    PropMode,
    TypeRef,
    UiEventSpec,
    UiInterface,
    UiInterfaceEntry,
    UiMethodSpec,
    UiParamSpec,
    UiPropSpec,
    UiWidgetSpec,
)


@ui_interface
class PySide6UiLibrary:
    ROOT_MODULE: ClassVar[str] = "PySide6"

    UI_INTERFACE: ClassVar[UiInterface] = UiInterface(
        name="PySide6UiLibrary",
        owner=None,
        entries=frozendict({
            "CQVideoWidget": UiInterfaceEntry(public_name="CQVideoWidget", kind="QVideoWidget"),
        }),
    )

    WIDGET_SPECS: ClassVar[frozendict[str, UiWidgetSpec]] = frozendict({
        'QVideoWidget': UiWidgetSpec(
            kind="QVideoWidget",
            mounted_type_name="PySide6.QtMultimediaWidgets.QVideoWidget",
            constructor_params=frozendict({
                "parent": UiParamSpec(name="parent", annotation=TypeRef(expr='PySide6.QtWidgets.QWidget | None'), default_repr='...'),
                "fullScreen": UiParamSpec(name="fullScreen", annotation=TypeRef(expr='bool | None'), default_repr='...'),
                "aspectRatioMode": UiParamSpec(name="aspectRatioMode", annotation=TypeRef(expr='PySide6.QtCore.Qt.AspectRatioMode | None'), default_repr='...'),
            }),
            props=frozendict({
                "parent": UiPropSpec(name="parent", annotation=TypeRef(expr='PySide6.QtWidgets.QWidget | None'), mode=PropMode.CREATE_ONLY_REMOUNT, constructor_name='parent', setter_kind=None, setter_name=None, getter_kind=None, getter_name=None, affects_identity=True),
                "fullScreen": UiPropSpec(name="fullScreen", annotation=TypeRef(expr='bool | None'), mode=PropMode.CREATE_UPDATE, constructor_name='fullScreen', setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "aspectRatioMode": UiPropSpec(name="aspectRatioMode", annotation=TypeRef(expr='PySide6.QtCore.Qt.AspectRatioMode | None'), mode=PropMode.CREATE_UPDATE, constructor_name='aspectRatioMode', setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "acceptDrops": UiPropSpec(name="acceptDrops", annotation=TypeRef(expr='bool'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "accessibleDescription": UiPropSpec(name="accessibleDescription", annotation=TypeRef(expr='QString'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "accessibleIdentifier": UiPropSpec(name="accessibleIdentifier", annotation=TypeRef(expr='QString'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "accessibleName": UiPropSpec(name="accessibleName", annotation=TypeRef(expr='QString'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "autoFillBackground": UiPropSpec(name="autoFillBackground", annotation=TypeRef(expr='bool'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "baseSize": UiPropSpec(name="baseSize", annotation=TypeRef(expr='QSize'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "childrenRect": UiPropSpec(name="childrenRect", annotation=TypeRef(expr='QRect'), mode=PropMode.READONLY, constructor_name=None, setter_kind=None, setter_name=None, getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "childrenRegion": UiPropSpec(name="childrenRegion", annotation=TypeRef(expr='QRegion'), mode=PropMode.READONLY, constructor_name=None, setter_kind=None, setter_name=None, getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "contextMenuPolicy": UiPropSpec(name="contextMenuPolicy", annotation=TypeRef(expr='Qt::ContextMenuPolicy'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "cursor": UiPropSpec(name="cursor", annotation=TypeRef(expr='QCursor'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "enabled": UiPropSpec(name="enabled", annotation=TypeRef(expr='bool'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "focus": UiPropSpec(name="focus", annotation=TypeRef(expr='bool'), mode=PropMode.READONLY, constructor_name=None, setter_kind=None, setter_name=None, getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "focusPolicy": UiPropSpec(name="focusPolicy", annotation=TypeRef(expr='Qt::FocusPolicy'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "font": UiPropSpec(name="font", annotation=TypeRef(expr='QFont'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "frameGeometry": UiPropSpec(name="frameGeometry", annotation=TypeRef(expr='QRect'), mode=PropMode.READONLY, constructor_name=None, setter_kind=None, setter_name=None, getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "frameSize": UiPropSpec(name="frameSize", annotation=TypeRef(expr='QSize'), mode=PropMode.READONLY, constructor_name=None, setter_kind=None, setter_name=None, getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "geometry": UiPropSpec(name="geometry", annotation=TypeRef(expr='QRect'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "height": UiPropSpec(name="height", annotation=TypeRef(expr='int'), mode=PropMode.READONLY, constructor_name=None, setter_kind=None, setter_name=None, getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "inputMethodHints": UiPropSpec(name="inputMethodHints", annotation=TypeRef(expr='QFlags<Qt::InputMethodHint>'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "isActiveWindow": UiPropSpec(name="isActiveWindow", annotation=TypeRef(expr='bool'), mode=PropMode.READONLY, constructor_name=None, setter_kind=None, setter_name=None, getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "layoutDirection": UiPropSpec(name="layoutDirection", annotation=TypeRef(expr='Qt::LayoutDirection'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "locale": UiPropSpec(name="locale", annotation=TypeRef(expr='QLocale'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "maximized": UiPropSpec(name="maximized", annotation=TypeRef(expr='bool'), mode=PropMode.READONLY, constructor_name=None, setter_kind=None, setter_name=None, getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "maximumHeight": UiPropSpec(name="maximumHeight", annotation=TypeRef(expr='int'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "maximumSize": UiPropSpec(name="maximumSize", annotation=TypeRef(expr='QSize'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "maximumWidth": UiPropSpec(name="maximumWidth", annotation=TypeRef(expr='int'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "minimized": UiPropSpec(name="minimized", annotation=TypeRef(expr='bool'), mode=PropMode.READONLY, constructor_name=None, setter_kind=None, setter_name=None, getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "minimumHeight": UiPropSpec(name="minimumHeight", annotation=TypeRef(expr='int'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "minimumSize": UiPropSpec(name="minimumSize", annotation=TypeRef(expr='QSize'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "minimumSizeHint": UiPropSpec(name="minimumSizeHint", annotation=TypeRef(expr='QSize'), mode=PropMode.READONLY, constructor_name=None, setter_kind=None, setter_name=None, getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "minimumWidth": UiPropSpec(name="minimumWidth", annotation=TypeRef(expr='int'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "modal": UiPropSpec(name="modal", annotation=TypeRef(expr='bool'), mode=PropMode.READONLY, constructor_name=None, setter_kind=None, setter_name=None, getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "mouseTracking": UiPropSpec(name="mouseTracking", annotation=TypeRef(expr='bool'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "normalGeometry": UiPropSpec(name="normalGeometry", annotation=TypeRef(expr='QRect'), mode=PropMode.READONLY, constructor_name=None, setter_kind=None, setter_name=None, getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "objectName": UiPropSpec(name="objectName", annotation=TypeRef(expr='QString'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "palette": UiPropSpec(name="palette", annotation=TypeRef(expr='QPalette'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "pos": UiPropSpec(name="pos", annotation=TypeRef(expr='QPoint'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "rect": UiPropSpec(name="rect", annotation=TypeRef(expr='QRect'), mode=PropMode.READONLY, constructor_name=None, setter_kind=None, setter_name=None, getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "size": UiPropSpec(name="size", annotation=TypeRef(expr='QSize'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "sizeHint": UiPropSpec(name="sizeHint", annotation=TypeRef(expr='QSize'), mode=PropMode.READONLY, constructor_name=None, setter_kind=None, setter_name=None, getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "sizeIncrement": UiPropSpec(name="sizeIncrement", annotation=TypeRef(expr='QSize'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "sizePolicy": UiPropSpec(name="sizePolicy", annotation=TypeRef(expr='QSizePolicy'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "statusTip": UiPropSpec(name="statusTip", annotation=TypeRef(expr='QString'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "styleSheet": UiPropSpec(name="styleSheet", annotation=TypeRef(expr='QString'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "tabletTracking": UiPropSpec(name="tabletTracking", annotation=TypeRef(expr='bool'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "toolTip": UiPropSpec(name="toolTip", annotation=TypeRef(expr='QString'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "toolTipDuration": UiPropSpec(name="toolTipDuration", annotation=TypeRef(expr='int'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "updatesEnabled": UiPropSpec(name="updatesEnabled", annotation=TypeRef(expr='bool'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "visible": UiPropSpec(name="visible", annotation=TypeRef(expr='bool'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "whatsThis": UiPropSpec(name="whatsThis", annotation=TypeRef(expr='QString'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "width": UiPropSpec(name="width", annotation=TypeRef(expr='int'), mode=PropMode.READONLY, constructor_name=None, setter_kind=None, setter_name=None, getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "windowFilePath": UiPropSpec(name="windowFilePath", annotation=TypeRef(expr='QString'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "windowIcon": UiPropSpec(name="windowIcon", annotation=TypeRef(expr='QIcon'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "windowIconText": UiPropSpec(name="windowIconText", annotation=TypeRef(expr='QString'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "windowModality": UiPropSpec(name="windowModality", annotation=TypeRef(expr='Qt::WindowModality'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "windowModified": UiPropSpec(name="windowModified", annotation=TypeRef(expr='bool'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "windowOpacity": UiPropSpec(name="windowOpacity", annotation=TypeRef(expr='double'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "windowTitle": UiPropSpec(name="windowTitle", annotation=TypeRef(expr='QString'), mode=PropMode.CREATE_UPDATE, constructor_name=None, setter_kind=AccessorKind.QT_PROPERTY, setter_name="setProperty", getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "x": UiPropSpec(name="x", annotation=TypeRef(expr='int'), mode=PropMode.READONLY, constructor_name=None, setter_kind=None, setter_name=None, getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
                "y": UiPropSpec(name="y", annotation=TypeRef(expr='int'), mode=PropMode.READONLY, constructor_name=None, setter_kind=None, setter_name=None, getter_kind=AccessorKind.QT_PROPERTY, getter_name="property", affects_identity=False),
            }),
            methods=frozendict({
                "setBaseSize": UiMethodSpec(
                    name="setBaseSize",
                    mode=MethodMode.CREATE_UPDATE,
                    params=(
                        UiParamSpec(name="basew", annotation=TypeRef(expr='int'), default_repr=None),
                        UiParamSpec(name="baseh", annotation=TypeRef(expr='int'), default_repr=None),
                    ),
                    source_props=("base_size_basew", "base_size_baseh"),
                    fill_policy=FillPolicy.RETAIN_EFFECTIVE,
                    constructor_equivalent=False,
                ),
                "setContentsMargins": UiMethodSpec(
                    name="setContentsMargins",
                    mode=MethodMode.CREATE_UPDATE,
                    params=(
                        UiParamSpec(name="left", annotation=TypeRef(expr='int'), default_repr=None),
                        UiParamSpec(name="top", annotation=TypeRef(expr='int'), default_repr=None),
                        UiParamSpec(name="right", annotation=TypeRef(expr='int'), default_repr=None),
                        UiParamSpec(name="bottom", annotation=TypeRef(expr='int'), default_repr=None),
                    ),
                    source_props=("contents_margins_left", "contents_margins_top", "contents_margins_right", "contents_margins_bottom"),
                    fill_policy=FillPolicy.RETAIN_EFFECTIVE,
                    constructor_equivalent=False,
                ),
                "setFixedSize": UiMethodSpec(
                    name="setFixedSize",
                    mode=MethodMode.CREATE_UPDATE,
                    params=(
                        UiParamSpec(name="w", annotation=TypeRef(expr='int'), default_repr=None),
                        UiParamSpec(name="h", annotation=TypeRef(expr='int'), default_repr=None),
                    ),
                    source_props=("fixed_size_width", "fixed_size_height"),
                    fill_policy=FillPolicy.RETAIN_EFFECTIVE,
                    constructor_equivalent=False,
                ),
                "setGeometry": UiMethodSpec(
                    name="setGeometry",
                    mode=MethodMode.CREATE_UPDATE,
                    params=(
                        UiParamSpec(name="x", annotation=TypeRef(expr='int'), default_repr=None),
                        UiParamSpec(name="y", annotation=TypeRef(expr='int'), default_repr=None),
                        UiParamSpec(name="w", annotation=TypeRef(expr='int'), default_repr=None),
                        UiParamSpec(name="h", annotation=TypeRef(expr='int'), default_repr=None),
                    ),
                    source_props=("geometry_x", "geometry_y", "geometry_width", "geometry_height"),
                    fill_policy=FillPolicy.RETAIN_EFFECTIVE,
                    constructor_equivalent=False,
                ),
                "setGraphicsEffect": UiMethodSpec(
                    name="setGraphicsEffect",
                    mode=MethodMode.CREATE_UPDATE,
                    params=(
                        UiParamSpec(name="effect", annotation=TypeRef(expr='PySide6.QtWidgets.QGraphicsEffect'), default_repr=None),
                    ),
                    source_props=("graphicsEffect",),
                    fill_policy=FillPolicy.RETAIN_EFFECTIVE,
                    constructor_equivalent=False,
                ),
                "setMaximumSize": UiMethodSpec(
                    name="setMaximumSize",
                    mode=MethodMode.CREATE_UPDATE,
                    params=(
                        UiParamSpec(name="maxw", annotation=TypeRef(expr='int'), default_repr=None),
                        UiParamSpec(name="maxh", annotation=TypeRef(expr='int'), default_repr=None),
                    ),
                    source_props=("maximumWidth", "maximumHeight"),
                    fill_policy=FillPolicy.RETAIN_EFFECTIVE,
                    constructor_equivalent=True,
                ),
                "setMinimumSize": UiMethodSpec(
                    name="setMinimumSize",
                    mode=MethodMode.CREATE_UPDATE,
                    params=(
                        UiParamSpec(name="minw", annotation=TypeRef(expr='int'), default_repr=None),
                        UiParamSpec(name="minh", annotation=TypeRef(expr='int'), default_repr=None),
                    ),
                    source_props=("minimumWidth", "minimumHeight"),
                    fill_policy=FillPolicy.RETAIN_EFFECTIVE,
                    constructor_equivalent=True,
                ),
                "setShortcutAutoRepeat": UiMethodSpec(
                    name="setShortcutAutoRepeat",
                    mode=MethodMode.CREATE_UPDATE,
                    params=(
                        UiParamSpec(name="id", annotation=TypeRef(expr='int'), default_repr=None),
                        UiParamSpec(name="enable", annotation=TypeRef(expr='bool'), default_repr='...'),
                    ),
                    source_props=("shortcut_auto_repeat_id", "shortcut_auto_repeat_enable"),
                    fill_policy=FillPolicy.RETAIN_EFFECTIVE,
                    constructor_equivalent=False,
                ),
                "setShortcutEnabled": UiMethodSpec(
                    name="setShortcutEnabled",
                    mode=MethodMode.CREATE_UPDATE,
                    params=(
                        UiParamSpec(name="id", annotation=TypeRef(expr='int'), default_repr=None),
                        UiParamSpec(name="enable", annotation=TypeRef(expr='bool'), default_repr='...'),
                    ),
                    source_props=("shortcut_enabled_id", "shortcut_enabled_enable"),
                    fill_policy=FillPolicy.RETAIN_EFFECTIVE,
                    constructor_equivalent=False,
                ),
                "setSizeIncrement": UiMethodSpec(
                    name="setSizeIncrement",
                    mode=MethodMode.CREATE_UPDATE,
                    params=(
                        UiParamSpec(name="w", annotation=TypeRef(expr='int'), default_repr=None),
                        UiParamSpec(name="h", annotation=TypeRef(expr='int'), default_repr=None),
                    ),
                    source_props=("size_increment_width", "size_increment_height"),
                    fill_policy=FillPolicy.RETAIN_EFFECTIVE,
                    constructor_equivalent=False,
                ),
                "setSizePolicy": UiMethodSpec(
                    name="setSizePolicy",
                    mode=MethodMode.CREATE_UPDATE,
                    params=(
                        UiParamSpec(name="horizontal", annotation=TypeRef(expr='PySide6.QtWidgets.QSizePolicy.Policy'), default_repr=None),
                        UiParamSpec(name="vertical", annotation=TypeRef(expr='PySide6.QtWidgets.QSizePolicy.Policy'), default_repr=None),
                    ),
                    source_props=("size_policy_horizontal", "size_policy_vertical"),
                    fill_policy=FillPolicy.RETAIN_EFFECTIVE,
                    constructor_equivalent=False,
                ),
                "setWindowFlags": UiMethodSpec(
                    name="setWindowFlags",
                    mode=MethodMode.CREATE_UPDATE,
                    params=(
                        UiParamSpec(name="type", annotation=TypeRef(expr='PySide6.QtCore.Qt.WindowType'), default_repr=None),
                    ),
                    source_props=("windowFlags",),
                    fill_policy=FillPolicy.RETAIN_EFFECTIVE,
                    constructor_equivalent=False,
                ),
                "setWindowState": UiMethodSpec(
                    name="setWindowState",
                    mode=MethodMode.CREATE_UPDATE,
                    params=(
                        UiParamSpec(name="state", annotation=TypeRef(expr='PySide6.QtCore.Qt.WindowState'), default_repr=None),
                    ),
                    source_props=("windowState",),
                    fill_policy=FillPolicy.RETAIN_EFFECTIVE,
                    constructor_equivalent=False,
                ),
            }),
            events=frozendict({
            }),
            mount_points=frozendict({
                "action": MountPointSpec(
                    name="action",
                    accepted_produced_type=TypeRef(expr='PySide6.QtGui.QAction'),
                    params=(
                    ),
                    min_children=0,
                    max_children=None,
                    apply_method_name=None,
                    sync_method_name=None,
                    place_method_name='insertAction',
                    append_method_name='addAction',
                    detach_method_name='removeAction',
                    replay_kind=MountReplayKind.ANCHOR_BEFORE,
                    prefer_sync=False,
                ),
                "layout": MountPointSpec(
                    name="layout",
                    accepted_produced_type=TypeRef(expr='PySide6.QtWidgets.QLayout'),
                    params=(
                    ),
                    min_children=0,
                    max_children=1,
                    apply_method_name='setLayout',
                    sync_method_name=None,
                    place_method_name=None,
                    append_method_name=None,
                    detach_method_name=None,
                    replay_kind=MountReplayKind.NONE,
                    prefer_sync=False,
                ),
            }),
            default_child_mount_point_name='layout',
            default_attach_mount_point_names=('layout', 'action'),
            child_policy=ChildPolicy.NONE,
        ),
    })

    class mounts:
        action = MountSelector.named("action")
        layout = MountSelector.named("layout")

    QT_PROPERTY_GETTER: ClassVar[str] = "property"
    QT_PROPERTY_SETTER: ClassVar[str] = "setProperty"

    @classmethod
    def __element(cls, *, kind: str, kwds: dict[str, Any]) -> UIElement:
        return UIElement(kind=kind, props=dict(kwds))

    @classmethod
    @pyrolyze
    def CQVideoWidget(
        cls,
        parent: PySide6.QtWidgets.QWidget | None = ...,
        *,
        fullScreen: bool | None = ...,
        aspectRatioMode: PySide6.QtCore.Qt.AspectRatioMode | None = ...,
        acceptDrops: bool | MissingType = MISSING,
        accessibleDescription: str | MissingType = MISSING,
        accessibleIdentifier: str | MissingType = MISSING,
        accessibleName: str | MissingType = MISSING,
        autoFillBackground: bool | MissingType = MISSING,
        baseSize: Any | MissingType = MISSING,
        contextMenuPolicy: Any | MissingType = MISSING,
        cursor: Any | MissingType = MISSING,
        enabled: bool | MissingType = MISSING,
        focusPolicy: Any | MissingType = MISSING,
        font: Any | MissingType = MISSING,
        geometry: Any | MissingType = MISSING,
        inputMethodHints: Any | MissingType = MISSING,
        layoutDirection: Any | MissingType = MISSING,
        locale: Any | MissingType = MISSING,
        maximumHeight: int | MissingType = MISSING,
        maximumSize: Any | MissingType = MISSING,
        maximumWidth: int | MissingType = MISSING,
        minimumHeight: int | MissingType = MISSING,
        minimumSize: Any | MissingType = MISSING,
        minimumWidth: int | MissingType = MISSING,
        mouseTracking: bool | MissingType = MISSING,
        objectName: str | MissingType = MISSING,
        palette: Any | MissingType = MISSING,
        pos: Any | MissingType = MISSING,
        size: Any | MissingType = MISSING,
        sizeIncrement: Any | MissingType = MISSING,
        sizePolicy: Any | MissingType = MISSING,
        statusTip: str | MissingType = MISSING,
        styleSheet: str | MissingType = MISSING,
        tabletTracking: bool | MissingType = MISSING,
        toolTip: str | MissingType = MISSING,
        toolTipDuration: int | MissingType = MISSING,
        updatesEnabled: bool | MissingType = MISSING,
        visible: bool | MissingType = MISSING,
        whatsThis: str | MissingType = MISSING,
        windowFilePath: str | MissingType = MISSING,
        windowIcon: Any | MissingType = MISSING,
        windowIconText: str | MissingType = MISSING,
        windowModality: Any | MissingType = MISSING,
        windowModified: bool | MissingType = MISSING,
        windowOpacity: float | MissingType = MISSING,
        windowTitle: str | MissingType = MISSING,
        base_size_basew: int | MissingType = MISSING,
        base_size_baseh: int | MissingType = MISSING,
        contents_margins_left: int | MissingType = MISSING,
        contents_margins_top: int | MissingType = MISSING,
        contents_margins_right: int | MissingType = MISSING,
        contents_margins_bottom: int | MissingType = MISSING,
        fixed_size_width: int | MissingType = MISSING,
        fixed_size_height: int | MissingType = MISSING,
        geometry_x: int | MissingType = MISSING,
        geometry_y: int | MissingType = MISSING,
        geometry_width: int | MissingType = MISSING,
        geometry_height: int | MissingType = MISSING,
        graphicsEffect: PySide6.QtWidgets.QGraphicsEffect | MissingType = MISSING,
        shortcut_auto_repeat_id: int | MissingType = MISSING,
        shortcut_auto_repeat_enable: bool | MissingType = MISSING,
        shortcut_enabled_id: int | MissingType = MISSING,
        shortcut_enabled_enable: bool | MissingType = MISSING,
        size_increment_width: int | MissingType = MISSING,
        size_increment_height: int | MissingType = MISSING,
        size_policy_horizontal: PySide6.QtWidgets.QSizePolicy.Policy | MissingType = MISSING,
        size_policy_vertical: PySide6.QtWidgets.QSizePolicy.Policy | MissingType = MISSING,
        windowFlags: PySide6.QtCore.Qt.WindowType | MissingType = MISSING,
        windowState: PySide6.QtCore.Qt.WindowState | MissingType = MISSING,
    ) -> None:
        call_native(cls.__element)(
            kind="QVideoWidget",
            parent=parent,
            fullScreen=fullScreen,
            aspectRatioMode=aspectRatioMode,
            acceptDrops=acceptDrops,
            accessibleDescription=accessibleDescription,
            accessibleIdentifier=accessibleIdentifier,
            accessibleName=accessibleName,
            autoFillBackground=autoFillBackground,
            baseSize=baseSize,
            contextMenuPolicy=contextMenuPolicy,
            cursor=cursor,
            enabled=enabled,
            focusPolicy=focusPolicy,
            font=font,
            geometry=geometry,
            inputMethodHints=inputMethodHints,
            layoutDirection=layoutDirection,
            locale=locale,
            maximumHeight=maximumHeight,
            maximumSize=maximumSize,
            maximumWidth=maximumWidth,
            minimumHeight=minimumHeight,
            minimumSize=minimumSize,
            minimumWidth=minimumWidth,
            mouseTracking=mouseTracking,
            objectName=objectName,
            palette=palette,
            pos=pos,
            size=size,
            sizeIncrement=sizeIncrement,
            sizePolicy=sizePolicy,
            statusTip=statusTip,
            styleSheet=styleSheet,
            tabletTracking=tabletTracking,
            toolTip=toolTip,
            toolTipDuration=toolTipDuration,
            updatesEnabled=updatesEnabled,
            visible=visible,
            whatsThis=whatsThis,
            windowFilePath=windowFilePath,
            windowIcon=windowIcon,
            windowIconText=windowIconText,
            windowModality=windowModality,
            windowModified=windowModified,
            windowOpacity=windowOpacity,
            windowTitle=windowTitle,
            base_size_basew=base_size_basew,
            base_size_baseh=base_size_baseh,
            contents_margins_left=contents_margins_left,
            contents_margins_top=contents_margins_top,
            contents_margins_right=contents_margins_right,
            contents_margins_bottom=contents_margins_bottom,
            fixed_size_width=fixed_size_width,
            fixed_size_height=fixed_size_height,
            geometry_x=geometry_x,
            geometry_y=geometry_y,
            geometry_width=geometry_width,
            geometry_height=geometry_height,
            graphicsEffect=graphicsEffect,
            shortcut_auto_repeat_id=shortcut_auto_repeat_id,
            shortcut_auto_repeat_enable=shortcut_auto_repeat_enable,
            shortcut_enabled_id=shortcut_enabled_id,
            shortcut_enabled_enable=shortcut_enabled_enable,
            size_increment_width=size_increment_width,
            size_increment_height=size_increment_height,
            size_policy_horizontal=size_policy_horizontal,
            size_policy_vertical=size_policy_vertical,
            windowFlags=windowFlags,
            windowState=windowState,
        )

GENERATION = '838d675e072d719e784fa29c8a8c31fa1ca08824f0fa486530ca58fbefcf477d'
